apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao
  namespace: monitoring
spec:
  provider:
    vault:
      server: http://k8s-openbao.openbao.svc:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: alertmanager
          serviceAccountRef:
            name: alertmanager
